
shell = "/bin/bash"

# mintty_bin_path=""
# ico_name = "ubuntu"
# title = "wsltty"
# mintty_config_dir = ""

[[distro]]
shell="/usr/bin/zsh"
title = 'wsltty'
name = 'manjaro-linux'
distro = 'manjaro-linux'

[[distro]]
shell = "/bin/bash"
title = "wsltty"
name = "manjaro-linux-test"
distro = "manjaro-linux-test"
